# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

coreLoop <- function(z, X, mat_x_m1, theta_vb, mu_theta_vb, tau_vb, sig2_theta_vb, c = 1) {
    invisible(.Call(`_bayesmqtl_coreLoop`, z, X, mat_x_m1, theta_vb, mu_theta_vb, tau_vb, sig2_theta_vb, c))
}

